apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: hotel-keycloak
  namespace: hotel-dev
spec:
  instances: 1
  hostname:
    hostname: "keycloak-hotel-dev.apps.inholland.hcs-lab.nl"
  http:
    httpEnabled: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  additionalOptions:
    - name: FEATURES
      value: 'hostname:v2'
    - name: PROXY
      value: edge
    - name: PROXY_ADDRESS_FORWARDING
      value: 'true'
    - name: PROXY_HEADERS
      value: xforwarded
    - name: HEALTH_ENABLED
      value: 'true'
    - name: LEGACY-OBSERVABILITY-INTERFACE
      value: 'true'
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            livenessProbe:
              httpGet:
                path: /health/live
                port: 8080
                scheme: HTTP
            readinessProbe:
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
            startupProbe:
              httpGet:
                path: /health/started
                port: 8080
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 15
              successThreshold: 1
              failureThreshold: 10